apiVersion: config.istio.io/v1alpha2
## Deny all access from istio-ingress
kind: RouteRule
metadata:
  name: iot-server-demo-seed-deny-route
spec:
  destination:
    name: iot-server-demo-seed
  match:
    # Limit this rule to istio ingress pods only
    source:
      name: istio-ingress
      labels:
        istio: ingress
  precedence: 1
  route:
  - weight: 100
  httpFault:
    abort:
      percent: 100
      httpStatus: 403 #Forbidden for all URLs

---
## Allow requests to /status prefix
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: status-route
spec:
  destination:
    name: iot-server-demo-seed
  match:
    # Limit this rule to istio ingress pods only
    source:
      name: istio-ingress
      labels:
        istio: ingress
    request:
      headers:
        uri:
          prefix: /iot
  precedence: 2 #must be higher precedence than the deny-route
  route:
  - weight: 100

