apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: iot-server-demo-ingest
  name: iot-server-demo-ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iot-server-demo-ingest
  template:
    metadata:
      labels:
        run: iot-server-demo-ingest
    spec:
      containers:
      - name: iot-server-demo-ingest
        image: navicore/iot-server-demo:0.1.80
        imagePullPolicy: Always
        env:
        - name: BOOTSTRAP
          value: "my-kafka:9092"
        - name: ROLE
          value: "ingest"
        livenessProbe:
          tcpSocket:
            port: 8081
        ports:
        - containerPort: 8081
          protocol: TCP
